name: Docker Compose Actions Workflow
on: pull_request
jobs:
  test-backend:
    name: test-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build images
        working-directory: ./codigo_fonte
        run: docker-compose build
