name: Docker Compose Actions Workflow
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build images
        working-directory: ./codigo_fonte
        run: docker-compose build
      - name: Test Backend
        run: docker images
